### ISSUE TITLE
Consider adding FromRubyToRust to SeaORM showcase!

### ISSUE THREAD

**Issue by billy1624** [nappa85/FromRubyToRust#1]
Hey @nappa85, feel free to submit a PR to showcase your project!
- https://github.com/SeaQL/sea-orm/issues/403

**Comment by nappa85** [comment]
Hi man,
thank you for your (probably automatic) message, but this is a repo related to a talk I kept at RustLab, it's not for "public" consumption.
Maybe someday I'll convert my talk into a blogpost...

**Comment by billy1624** [comment]
Hey @nappa85, let me know when the blogpost is published :D
